### ISSUE TITLE
Unable to resolve module `crypto` from `node_modules/@polkadot/wasm-crypto/crypto-polyfill.js

### ISSUE THREAD

**Issue by JeremyConnor** [polkadot-js/wasm#138]
I was trying to use Polkadot.js with my react-native app. For this purpose, I installed using the following commands.
```
yarn add @polkadot/wasm-crypto @polkadot/util
yarn add @polkadot/api @polkadot/api-contract
```
Just to see if the app was able to interact with the Polkadot, I used [this](https://github.com/hashpire/polkadotjsWithReactNative/blob/master/App.js) sample code. Following which I got the error. 
![Screenshot from 2020-11-06 17-13-03](https://user-images.githubusercontent.com/73089748/98364171-53caad80-2056-11eb-9a0c-b06d08128d23.png)

**Comment by jacogr** [comment]
You need to provide it yourself, see for instance https://github.com/polkadot-js/ui/blob/master/packages/exampleReactNative/metro.config.js#L17

**Comment by JeremyConnor** [comment]
Thanks for pointing it out. I will follow it and let you know.

**Comment by JeremyConnor** [comment]
> You need to provide it yourself, see for instance https://github.com/polkadot-js/ui/blob/master/packages/exampleReactNative/metro.config.js#L17

I followed this file to update metro.config.js file of my react native app, and then installed react-native-crypto. After doing this, I get the error, 
error: package.json not found in path.

**Comment by jacogr** [comment]
That is a local issue, not a daily RN dev, so honestly cannot help you debug Expo/metro in this case.

**Comment by JeremyConnor** [comment]
> You need to provide it yourself, see for instance https://github.com/polkadot-js/ui/blob/master/packages/exampleReactNative/metro.config.js#L17

Thanks! This helped to solve it.
