### ISSUE TITLE
Centos 7

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/wasm#164]
Logging on behalf of @SleepingNext since the issue is completely different and wrongly allocated to a resolved long-running Chrome-increases-memory-on-refresh issue.

On CentOs 7 Node runs out of memory when creating the WASM bundle. Doesn't do the same under Docker on the same machine.

**Comment by jacogr** [comment]
1. Do a `node --version` on the Centos having the issue
2. do the same in the docker container (and the machines where it doesn't occur)

If you read the Node.js (depending on version) pre-allocates (they call it "reservation") around 1GB+ virtual memory up-front when instantiating WASM. So depending on the version (current LTS is optimal, having had a number of fixes over older versions), the default memory may not be enough and may need to be increased via the Node memory flags.

**Comment by SleepingNext** [comment]
Both local and docker use Node v13.8.0. I read this: https://superuser.com/questions/48505/how-to-find-virtual-memory-size-and-cache-size-of-a-linux-system that says virtual memory in Linux is indicated with the swap. Then, it means that mine is not enough, sir?
![image (10)](https://user-images.githubusercontent.com/42561768/102753255-7cf09480-439d-11eb-83bd-dd782aaab532.png)

**Comment by jacogr** [comment]
It is about the memory available inside the Node.js process, not what is on the system. Node.js has limits as to what it will use, depending on what is available on the system, 64-bit vs 32-bit environments and how it was compiled. 

Generally you can tweak it, i.e. see https://support.circleci.com/hc/en-us/articles/360009208393-How-can-I-increase-the-max-memory-for-Node-

aka passing `node --max_old_space_size=4096 ./script.js`

**Comment by SleepingNext** [comment]
I've tried that before. But, still...
![image (11)](https://user-images.githubusercontent.com/42561768/102754541-b924f480-439f-11eb-9eb9-c449ee5a4526.png)

**Comment by jacogr** [comment]
Not sure which detected limit trips it up, it originates from here in Node.js - https://chromium.googlesource.com/v8/v8/+/644556e6ed0e6e4fac2dfabb441439820ec59813/src/wasm/module-instantiate.cc#1244

The only thing I would suggest is using an Node.js LTS (14.x is active, see https://nodejs.org/en/about/releases/#releases), maybe that does improve. 

(It is def. not version-specific since you mentioned the 2 Node.js versions are the same between the environments, but rather environment-specific, but that is a bit out of my wheelhouse to try and extract the options the 2 run with)
