### ISSUE TITLE
Node.js import causing Webpack build problem

### ISSUE THREAD

**Issue by ronanyeah** [polkadot-js/wasm#177]
While using `@polkadot/extension-dapp` with Webpack, I encountered a problem which I have narrowed down to [this line](https://github.com/polkadot-js/wasm/blob/1bb6db86f7e8df1ceddbba14649541431b67b08d/packages/wasm-crypto-wasm/src/buffer.ts#L4).

![Screenshot from 2021-02-22 01-31-26](https://user-images.githubusercontent.com/9598261/108646478-e444c680-746a-11eb-9b1b-6a6866b4731f.png)

Are polyfills for Node.js modules required in order to import Polkadot npm packages?

**Comment by jacogr** [comment]
Are you using Webpack 5?

in WP4, the builder used to auto polyfill. In WP5 That behavior has changed. More details here in their changelog - https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

**Comment by ronanyeah** [comment]
Yes I am using Webpack 5. Is Polkadot still in the process of supporting it? I am aware of the recent polyfill changes.

**Comment by jacogr** [comment]
Both the apps UI and the extension are using WP5. (Obviously with polyfills that are not auto-included anymore since the WP4 -> WP5 move)

**Comment by ronanyeah** [comment]
Is there a plan to remove the dependency on polyfills?

**Comment by jacogr** [comment]
For `Buffer` in this case, no. This used by `util-crypto` which has a number of deps with `Buffer` so even if removed here, the requirement would still be there. (Until upstream deps move to using only Uint8Array, e.g. which is what own-code uses) 

In a number of places, Buffer dependencies have been removed, alongside `process`, `crypto`, but it is always an on-going process and easy with areas with direct control.

**Comment by ronanyeah** [comment]
I am willing to help out with this if PRs would be appreciated. Which repo would be best to approach first?

**Comment by jacogr** [comment]
PRs are always welcome - the utilities/crypto (which are the major users) are located at https://github.com/polkadot-js/common

**Comment by jacogr** [comment]
Actually removed the Buffer dependency in https://github.com/polkadot-js/wasm/pull/178 (but util-crypto is the big issue when including)
