### ISSUE TITLE
WebAssembly is not available in your environment

### ISSUE THREAD

**Issue by rvalle** [polkadot-js/wasm#228]
Hi!

How can I import this package in a non-webassembly environment?

I am currently generating client side polkadotJS mockups for testing purposes, but my JS VM has no Webassembly, I am using webpack with babel to generate the client bundle.

I can see by issue #19 that seems to be possible to use some kind of polyfill. Looks like there is two flavors of this package implementation depending on the capabilities of the javascript environment.

But I can't find the selection mechanism, that seems not to be working for me, or how to "force" a particular implementation to be used. I can see that in the unit test ```global.Webassembly``` is set to ```null```, but does seems not to do the trick for me.

Everything I try seems to end on "Webassembly not available in your environment".

How can I generate a webpack bundle for such a  envirobment?

**Comment by jacogr** [comment]
Webpack? Add an alias for -

`@polkadot/wasm-crypto-asmjs/empty.js`

to

`@polkadot/wasm-crypto-asmjs/data.js`

Assuming ESM, cjs bundles would have the .cjs extension. With this is will fallback to the asmjs build as bundled (It is not included by default, apart from RN, since it bloats the bundles a lot)

This is what happens for RN vs browser/Node, see https://github.com/polkadot-js/wasm/blob/master/packages/wasm-crypto-asmjs/package.json#L21-L23

**Comment by rvalle** [comment]
thanks @jacogr don't know how I missed the: ```  "react-native": "data.js" ```

I am trying to use webpack to alias a single module file without success, I can only find documentation for aliasing the whole module. Will let you knwo how it goes...

**Comment by jacogr** [comment]
So this should do the trick (not sure which one, the first seems more correct since we import from `@polkadot/wasm-crypto-asmjs` in `@polkadot/wasm-crypto`) -

```js
alias: {
  '@polkadot/wasm-crypto-asmjs': require.resolve('@polkadot/wasm-crypto-asmjs/data.js')
}
```

or ...

```js
alias: {
  '@polkadot/wasm-crypto-asmjs/empty.js': require.resolve('@polkadot/wasm-crypto-asmjs/data.js')
}
```

**Comment by rvalle** [comment]
Thanks! It is not complaining now about missing Webassembly
