### ISSUE TITLE
exports.js file missing @polkadot/wasm-crypto@0.13.0-beta.0 Version

### ISSUE THREAD

**Issue by qalqi** [polkadot-js/wasm#24]
Started to test @polkadot/wasm-crypto@0.13.0-beta.0 Version in react native
Getting the following error
Unable to resolve module `./exports` from `node_modules/@polkadot/wasm-crypto/index.js

Indeed, none of these files exist
`node_modules/@polkadot/wasm-crypto/exports(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`

**Comment by qalqi** [comment]
Also, tried creating exports.js with contents from the repo in the specified folder.

Metro bundler in react-native doesn't progress. Paused at 99%

**Comment by jacogr** [comment]
Ok, will push a fix for that one, sorry, naming got in the way. (Very weird that the tests didn't pick it up)

EDIT: Not a testing issue, the new file was not specified. https://github.com/polkadot-js/wasm/commit/0d9f526a5f8582b7ed9d27da0545d510b14ba13c

0.13.0-beta.1 should be available in 12-15 mins as soon as CI completes

**Comment by jacogr** [comment]
Should be fixed in 0.13.0-beta.1 - sorry about that, have not managed to have a gap yet to pull it in directly into `@polkadot/util-crypto` (and rollout to the rest of the polkadot-js repos) which would have shown this issue.
