### ISSUE TITLE
Inconsistency between documentation and code

### ISSUE THREAD

**Issue by tjwelde** [polkadot-js/wasm#324]
Hi,

the comment here:
https://github.com/polkadot-js/wasm/blob/8cc2a167e1a3a26cb8b4213dc2c4baac9bec8afc/packages/wasm-crypto/src/rs/ed25519.rs#L25

does not seem to reflect to what is really happening. 
While trying to reflect on how the key generation algorithm works in detail and trying to recreate it, I was left confused, because the secret key is 32 bytes long, but the documentation says it is 64 bytes. It also says, that the 64 bytes are followed by 32 bytes of public key, but the total returned vector is 64 bytes long, not 96 bytes.

Additionally, where the wasm code is called from (https://github.com/polkadot-js/common/blob/3597a4eb4e0cf9985104568058c5cd23701bbaed/packages/util-crypto/src/ed25519/pair/fromSeed.ts#L30), the whole 64 byte array is taken for the private key and the second half of that array is taken as the public key. For the public key that is fine, but the private key than consists of both the secret key _and_ the public key. Is that correct how it is?
If yes I would suggest we change the documentation on the `ext_ed_from_seed` function.

**Comment by jacogr** [comment]
Good catch - this is somewhere between changing Rust libs and not updating the comment. The reason for the "seed + public" as the secret on the JS side is to keep compatibility between the tweetnacl and Rust libs.
