### ISSUE TITLE
Beta release for each hour?

### ISSUE THREAD

**Issue by ianhe8x** [polkadot-js/wasm#40]
@jacogr looks like something wrong with your CD pipeline

**Comment by jacogr** [comment]
Stopped 11hrs ago - indeed a bug.

**Comment by jacogr** [comment]
Fixed in https://github.com/polkadot-js/wasm/commit/ab61af29ab6f1313ab7b3e7d578e405763b7fa6c

(Really though I had these wrapped, obviously not)
