### ISSUE TITLE
Out-of-bound object update

### ISSUE THREAD

**Issue by fukaraadam** [polkadot-js/wasm#550]
* **I'm submitting a small bug report for trying to dynamically extend an object. **

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I have found that, 2 loops have wrong limits and as a result, code tries to assign value to object with a key out-of-bound.
[First bug](https://github.com/polkadot-js/wasm/blob/61624a627b5e8c3359ccb2824346d6e1d6510392/packages/wasm-util/src/base64.ts#L27-L43)
In last loop of above example, code does this:
```
out[out.length] = 0;
```
This is ignored in node (v18) and browser (tested on Chrome). Furthermore, it crashes on specific environments (e.g. QuickJS)

Test in Node:
![image](https://github.com/polkadot-js/wasm/assets/24752545/de53ae2a-72a5-4d2a-b491-f04cec30214e)
Output:
![image](https://github.com/polkadot-js/wasm/assets/24752545/043bcd2b-3d8a-44c5-a8ca-41450fdfc867)

To fix first bug, changing from `count = out.length` to `count = out.length-1` will be enough.
[Second bug](https://github.com/polkadot-js/wasm/blob/61624a627b5e8c3359ccb2824346d6e1d6510392/packages/wasm-util/src/fflate.ts#L95C9-L95C9)
This line tried this `++l[-1]` many times, first time called by [here](https://github.com/polkadot-js/wasm/blob/61624a627b5e8c3359ccb2824346d6e1d6510392/packages/wasm-util/src/fflate.ts#L247C39-L247C39).

I will update here if I find other places (and if you would like to handle this issue)

* **What is the motivation for changing the behavior?**
I am trying to use polkadot.js with QuickJS (to use it in Godot game engine). It causes to errors in QuickJS. Also it causes unnecessary operations in other environments and may lead to other bugs in future.

* **Please tell us about your environment:**

  - Version: 7.3.1
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [x] Other (QuickJS)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
Would appreciate feedback on https://github.com/polkadot-js/wasm/releases/tag/v7.3.2 which includes the 2 linked PRs.

**Comment by fukaraadam** [comment]
I had already forked on those PRs, while waiting the relese and they worked like a charm. For now, I couldn't find similar error any where else. This can be closed successfully.
