### ISSUE TITLE
ERROR: Unable to initialize @polkadot/wasm-crypto 1.2.1

### ISSUE THREAD

**Issue by xwartz** [polkadot-js/wasm#82]
WebAssembly does not work with react-native webview. 

```
ReferenceError: Can't find variable: WebAssembly
```

**Comment by jacogr** [comment]
So for things like React-Native, there is an asm.js wrapper - it is enabled here when it detects "react-native", https://github.com/polkadot-js/wasm/blob/master/packages/wasm-crypto/package.json#L18

So basically what that does (assuming the bundler doesn't ignore the field) is to swap the bundle to asm.js. (Works really well in this sample as well - https://github.com/polkadot-js/ui/tree/master/packages/exampleReactNative)

**Comment by jacogr** [comment]
Closing.

**Comment by dractw** [comment]
Works well with react-native wich resolves `react-native` field in package.json, for apps builded with cordova it doesn't work without hardcoded `main` field, pointed to `data` instead `empty`.
